### ISSUE TITLE
Didn't you share the trained models?

### ISSUE THREAD

**Issue by zhouhao-learning** [justinshenk/fer#4] opened 2019-07-17 05:47 UTC
Hello, I'm glad to see your code, but when I execute `python video-example.py', the probability of predicting each expression is almost the same. There is no obvious difference. Like the results shown below, it seems that the probability of `happy'should be greater, but the result is not the same:

![test79](https://user-images.githubusercontent.com/24581773/61350232-75b88380-a899-11e9-8ff2-1327006c4b29.jpg)

So I think it may be that your public model is not well trained. I would like to ask if you can publish your trained model?

**Comment by justinshenk** [comment] 2019-07-17 11:23
Hi Kyrie,

Thanks for your message. I have seen this error caused by insufficient
preprocessing, rather than issues with the model.

Can you maybe share the video clip with me for testing?
shenkjustin@gmail.com. I will take a look at it and let you know when it is
fixed.

Justin

**Comment by zhouhao-learning** [comment] 2019-07-17 11:35
@justinshenk 
Ok, I have sent you the test video, please check it.

**Comment by zhouhao-learning** [comment] 2019-07-17 11:39
@justinshenk 
The image prediction results I got from running `example.py` are also obviously wrong, so I suspect that it should be a model problem, not quite a problem with data preprocessing.
![成龙_draw](https://user-images.githubusercontent.com/24581773/61372745-89301280-a8ca-11e9-8f7d-df3175ec834b.jpg)

**Comment by justinshenk** [comment] 2019-07-17 17:38
The issue with the video was due to nesting TensorFlow sessions (not recommended). Fixed in f1322de80cd4fd6eb6ed55d1da73d075beba4dcb. Please try again and let me know how it goes.

**Comment by justinshenk** [comment] 2019-07-17 17:40
Example: ![image](https://user-images.githubusercontent.com/10270308/61397645-a369f080-a8ca-11e9-9abd-26a95adbd398.png)

**Comment by zhouhao-learning** [comment] 2019-07-18 01:33
@justinshenk 
Ok, thank you very much for your reply.After you modify it, the effect is obviously correct.

**Closed** 2019-07-18 01:33 UTC
